version: '3.8'

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile.back
    networks:
      - default_net

  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    networks:
      - default_net

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx-proxy
    depends_on:
      - back
      - front
    networks:
      - default_net
    ports:
      - "80:80"
      # - "443:443"

networks:
  default_net:
    name: default_net
    external: true