FROM node:alpine AS build-alpine

WORKDIR /app
COPY ./frontend/package.json /app/package.json
RUN npm install
COPY ./frontend /app
RUN npm run build

FROM nginx:stable-alpine

COPY --from=build-alpine /app/build /usr/share/nginx/html
COPY ./etc/nginx-front.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD [ "nginx", "-g", "daemon off;" ]